export const ADD_MEMES = `ADD_MEMES`;
export const CHANGE_STATUS_LIKE_MEM = `CHANGE_STATUS_LIKE_MEM`;
export const FILTERED_ALL = `FILTERED_MEMES`;
export const FILTERED_LOVER = `FILTERED_LOVER`;
export const CHANGE_MENU_STATUS = `CHANGE_MENU_STATUS`;
